EXIT_CODE_FINAL_STATUS_SUCCESS = 0
EXIT_CODE_UNKNOWN_ERROR = 3


# Input Issues
EXIT_CODE_INVALID_CREDENTIALS = 200
EXIT_CODE_SYNC_INVALID_ID = 201
EXIT_CODE_BAD_REQUEST = 202

# Sync Status
EXIT_CODE_FINAL_STATUS_FAILED = 210
EXIT_CODE_FINAL_STATUS_RUNNING = 211
EXIT_CODE_UNKNOWN_STATUS = 212
